### PR TITLE
Initial Project Demonstrated Code Plus other Functionalities

### PR DESCRIPTION
**Pull request by OdongAlican**
## In this task, I was able to complete the following
- Created the IndividualCustomer related components
- Add the respective styles
- Deploy the current state of the project on heroku

### Waiting for feedback !!

### CODE REVIEW

**Comment by Ivonian** [comment]
Hi @OdongAlican I also noted that the static data drop downs like title, nationality are not getting values from the api, they are hard coded. The values and text for the dropdowns should come from api/database. There is an api endpoint called GetStaticData, that will retrieve all the necessary data with one call. Perhaps you call the endpoint on form load.

**Comment by OdongAlican** [comment]
That's very possible. I will implement that

**Comment by benviktech** [comment]
@OdongAlican , kindly work on the feedback from @Ivonian and @claude, before i go a head to merge. please hit me up when changes are all good

**Comment by OdongAlican** [comment]
Kool

**Pull request merged**
